---
- name: create clients.yml-revisions directory
  file: path={{playbook_dir}}/clients.yml-revisions state=directory mode=0755
  tags: init 

- name: create config directory layout
  file: path={{playbook_dir}}/{{item}}  state=directory mode=0755
  with_items:
    - config
    - config/remap.d
    - config/banjax.d
  tags: init

- name: check if autobrains_update.sh exists 
  stat: path={{playbook_dir}}/autobrains_update.sh
  register: autobrains_update 
  ignore_errors: True
  tags: init 

- name: Create autobrains_update.sh script
  template: src=autobrains_update.sh.j2 dest={{playbook_dir}}/autobrains_update.sh mode=755
  when: not autobrains_update.stat.exists
  tags: init 
