---
- name: create clients.yml-revisions directory
  file:
    path: "clients.yml-revisions"
    state: directory
    mode: '0755'
  tags:
    - init
    - setup

- name: create directory layout
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - config
    - config/remap.d
    - config/banjax.d
    - config/rundata
    - config/logs
    - bin
  tags:
    - init
    - setup

- name: check if autobrains_update.sh exists
  stat:
    path: "autobrains_update.sh"
  register: autobrains_update
  ignore_errors: True
  tags:
    - init
    - setup

- name: Create autobrains_update.sh script
  template:
    src: autobrains_update.sh.j2
    dest: "autobrains_update.sh"
    mode: '755'
  when: not autobrains_update.stat.exists
  tags:
    - init
    - setup
